languages:
  Ruby: false
  JavaScript: true
  PHP: true
  Python: false

exclude_paths:
  - "vendor/*"
  - "public/web/jquery.min.js"
  - "public/web/bootstrap/js/bootstrap.min.js"
  - "public/web/bootstrap/css/bootstrap.min.css"
  - "public/web/bootstrap/fonts/*"
