# Attogram Framework - .travis.yml v0.0.5
# Travis CL configuration for https://travis-ci.org/attogram/attogram

language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm
  - nightly

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly

before_script:
  - composer self-update
  - composer --ignore-platform-reqs install
  - USE_OLD_PHPUNIT=0
  - if [[ "$TRAVIS_PHP_VERSION" = "5.3" ]]; then USE_OLD_PHPUNIT=1; fi;
  - if [[ "$TRAVIS_PHP_VERSION" = "5.4" ]]; then USE_OLD_PHPUNIT=1; fi;
  - if [[ "$USE_OLD_PHPUNIT" = "1" ]]; then wget https://phar.phpunit.de/phpunit-old.phar; fi;

script:
  - if [[ "$USE_OLD_PHPUNIT" = "1" ]]; then php phpunit-old.phar --debug --configuration=phpunit.xml; else phpunit --debug --configuration=phpunit.xml; fi;
