language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm
  - nightly

matrix:
  fast_finish: true
  allow_failures:
    - php: 5.3
    - php: 5.4
    - php: nightly

before_script:
  - composer self-update
  - composer --ignore-platform-reqs --verbose install

script:
  - phpunit --verbose --debug
