# Attogram Framework - .travis.yml v0.0.2
# Travis CL configuration for https://travis-ci.org/attogram/attogram

language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm
  - hhvm-nightly
  - nightly

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly
    - php: hhvm-nightly

before_script:
  - composer self-update
  - composer --ignore-platform-reqs --verbose install
  - wget https://phar.phpunit.de/phpunit-old.phar

script:
#  - phpunit --verbose --debug
  - php phpunit-old.phar --verbose --debug
